%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                       %
%                                       %
%   plot six sections of data and fit   %
%                                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function PlotData2(Tau_1, Tau_2, Data, Fit)

   figure
   zmin = min(min(Data));
   zmax = max(max(Data));

[m,n] = size(Data);

	
	subplot(2,3,1)
	PlotFig(1, Tau_2, Data(:,1), 'M(\tau_2)', ...
	['\tau_1 = ', num2str(Tau_1(1)), ' sec'], zmin, zmax, 'b-', ...
	 'linear', 'linear')
	hold on
	PlotFig(1, Tau_2, Fit(:,1), 'M(\tau_2)', ...
	['\tau_1 = ', num2str(Tau_1(1)), ' sec'], zmin, zmax, 'r-', ...
		 'linear', 'linear')

	
	subplot(2,3,2)
	PlotFig(1, Tau_2, Data(:,floor(end/2)), 'M(\tau_2)', ...
	['\tau_1 = ', num2str(Tau_1(floor(end/2))), ' sec'], zmin, zmax, 'bo', ...
            'linear', 'linear')
	hold on
	PlotFig(1, Tau_2, Fit(:,floor(end/2)), 'M(\tau_2)', ...
	['\tau_1 = ', num2str(Tau_1(floor(end/2))), ' sec'], zmin, zmax, 'r-', ...
	 'linear', 'linear')
	
	subplot(2,3,3)
	PlotFig(1, Tau_2, Data(:,end), 'M(\tau_2)', ...
	['\tau_1 = ', num2str(Tau_1(end)), ' sec'], zmin, zmax, 'bo', ...
            'linear', 'linear')
	hold on
	PlotFig(1, Tau_2, Fit(:,end), 'M(\tau_2)', ...
	['\tau_1 = ', num2str(Tau_1(end)), ' sec'], zmin, zmax, 'r-', ...
	 'linear', 'linear')
	
	
	subplot(2,3,4)
	PlotFig(Tau_1, 1, Data(1,:), 'M(\tau_1)', ...
	['\tau_2 = ', num2str(Tau_2(1)), ' sec'], zmin, zmax, 'bo', ...
            'log', 'linear')
	hold on
	PlotFig(Tau_1, 1, Fit(1,:), 'M(\tau_1)', ...
	['\tau_2 = ', num2str(Tau_2(1)), ' sec'], zmin, zmax, 'r-', ...
	 'log', 'linear')
	
	subplot(2,3,5)
	PlotFig(Tau_1, 1, Data(end/2,:), 'M(\tau_1)', ...
	['\tau_2 = ', num2str(Tau_2(end/2)), ' sec'], zmin, zmax, 'bo', ...
            'log', 'linear')
	hold on
	PlotFig(Tau_1, 1, Fit(end/2,:), 'M(\tau_1)', ...
	  ['\tau_2 = ', num2str(Tau_2(end/2)), ' sec'], zmin, zmax, 'r-', ...
	 'log', 'linear')
	
	subplot(2,3,6)
	PlotFig(Tau_1, 1, Data(end,:), 'M(\tau_1)', ...
	['\tau_2 = ', num2str(Tau_2(end)), ' sec'], zmin, zmax, 'bo', ...
            'log', 'linear')
	hold on
	PlotFig(Tau_1, 1, Fit(end,:), 'M(\tau_1)', ...
	['\tau_2 = ', num2str(Tau_2(end)), ' sec'], zmin, zmax, 'r-', ...
	 'log', 'linear')
